version: "3"
services:
  app:
    image: suecharo/genpei:1.0.2
    container_name: genpei
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:${PWD}
    environment:
      - GENPEI_HOST=0.0.0.0
      - GENPEI_PORT=8080
      - GENPEI_DEBUG=False
      - GENPEI_RUN_DIR=${PWD}/run
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["genpei"]
