version: "3"
services:
  app:
    image: docker.pkg.github.com/suecharo/genpei/genpei:1.0.1
    container_name: genpei
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ${PWD}:${PWD}
    environment:
      - GENPEI_HOST=0.0.0.0
      - GENPEI_PORT=8080
      - GENPEI_DEBUG=False
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["genpei"]
